### ISSUE TITLE
Bug: incompatibility with the new word animation (A/B test)

### ISSUE THREAD

**Issue by rom528** [blmage/duolingo-word-bank-dnd#37]
It stopped working a few days ago.  please, please fix it to work again? Very useful and we miss it.

**Comment by blmage** [comment]
Thanks for the report! 

I could not reproduce the problem on Chrome or Firefox, could you give a little more details about your environment?

**Comment by bumpyy** [comment]
I'm using Edge, when i release the button after i drag the word, all the word just get deselect.

**Comment by blmage** [comment]
@Bump-san There has been a UI update, version **1.1.5** should fix this, can you try again?
Also, thanks for warning me!

**Comment by bumpyy** [comment]
still the same, i also try to install it on chrome but same problem

**Comment by blmage** [comment]
@Bump-san this is weird, I can't reproduce the problem on my side on different browsers..

Do you use any other extension(s) for Duolingo?

If not, I would tend to believe that this is due to a change behind an A/B test, in which case it will be difficult to reproduce.

**Comment by bumpyy** [comment]
Perhaps, I'll try some test
And I'll try to fix it myself (tho i have. No experience working with javascript and extension, so no promise)

**Comment by blmage** [comment]
After having given it more thought, it seems that the extension fails to find the words that were previously selected, which means that the text of the buttons is somehow different depending on their location (answer or word bank).

On which course have you tried it?

**Comment by blmage** [comment]
Thanks to @alexseyk's demo in #38, I can confirm that this is an A/B tested feature (`web_fly_tokens_into_place`).

One solution would be to wait for the words to return to their original place before reselecting them, but in order to work on it, I still need to find a reliable and easy way to force the activation of a given A/B test.

Since this seems to become more widespread, I'll look into this asap!

**Comment by bumpyy** [comment]
Well one thing that i discover is that if you zoom or use device emulation via developer tool to make the site use phone layout, the extension work fine.

**Comment by blmage** [comment]
@Bump-san Yes, it seems like the new animation is disabled under a given breakpoint.

In any case, related compatibility problems should be fixed in version **1.2.0**.

@rom528 @Bump-san @alexseyk could you install it and report back if everything works fine?

**Comment by bumpyy** [comment]
It work, but have some wild animation
but work nonetheless
![test](https://user-images.githubusercontent.com/28483765/101013304-ab493400-3596-11eb-97db-38408ec12034.gif)

**Comment by alexseyk** [comment]
+1

**Comment by blmage** [comment]
@Bump-san @alexseyk Thanks!

The animation is due to how the extension works under the hood (it removes the words before adding them again, so that Duolingo takes the changes into account).

I'll give a try at hiding the words when they are "flying", and probably do a quick poll to find out which solution looks the best (unless I find a solution to cut the original animation entirely).

**Comment by alexseyk** [comment]
I don't care that words are flying nevertheless i will welcome elimination of such feature

**Comment by alexseyk** [comment]
FYI: there is no animation in Yandex browser :)

**Comment by blmage** [comment]
Finally got some time to work on this!

This is probably the best result we can get, given how little control we have over the animation:

https://user-images.githubusercontent.com/25432517/108092290-db27b400-707c-11eb-9d03-66603945247c.mp4

What do you think of it?

**Comment by alexseyk** [comment]
Fine by me but honestly can't really see the difference (improvement)

**Comment by bumpyy** [comment]
That's great, appreciate the effort

**Comment by blmage** [comment]
Version `2.0.0` now provides an option to "tone down" this animation! (a demo is available [here](https://github.com/blmage/duolingo-word-bank-dnd#tone-down-word-animation))
